"""Typed state schema, reducers, and lifecycle models for LangGraph multi-agent execution (FR-OR-2, FR-OR-7, FR-OR-9).

Architectural Concepts Explained:
--------------------------------
1. Why LangGraph Typed State Matters:
   - In complex multi-agent systems, agents pass context between planning, execution, and evaluation.
   - If state is an untyped dictionary, typos cause silent errors, schema mismatches, and debugging nightmares.
   - Using typed structures ensures every node in the graph reads and writes deterministic attributes.

2. State Reducers (FR-OR-2):
   - In LangGraph, when a node returns `{"events": [new_event]}`, the default behavior is to OVERWRITE
     the previous `events` list.
   - For append-only audit histories, tool logs, or artifacts, overwriting would erase prior history!
   - Reducers define merge semantics:
     `Annotated[list[StepEvent], append_events]` tells LangGraph:
     "When a node yields new events, append them to the existing list instead of replacing it."

3. The Run Lifecycle State Machine (FR-OR-9):
   - QUEUED: Run received via API, waiting for worker assignment.
   - PLANNING: Supervisor or planner node is breaking the user goal into structured tasks.
   - RUNNING: Specialized agents (Document RAG, Web, SQL, etc.) are actively executing steps.
   - AWAITING_APPROVAL: Execution interrupted at a high-risk policy checkpoint (e.g. SQL write).
   - COMPLETED: All planned steps finished and critic validated the final output.
   - FAILED: Fatal error occurred, budget exceeded, or unrecoverable agent failure.
   - CANCELLED: Explicitly aborted by user or timeout.
"""

from datetime import UTC, datetime
from enum import StrEnum
from typing import Annotated, Any, TypedDict
from uuid import uuid4

from pydantic import BaseModel, Field


class RunStatus(StrEnum):
    """Lifecycle state of an orchestration run (FR-OR-9)."""

    QUEUED = "queued"
    PLANNING = "planning"
    RUNNING = "running"
    AWAITING_APPROVAL = "awaiting_approval"
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELLED = "cancelled"


class AgentType(StrEnum):
    """Specialized agent subgraphs recognized by the supervisor (FR-OR-1)."""

    SUPERVISOR = "supervisor"
    DOCUMENT_RAG = "document_rag"
    WEB_RESEARCH = "web_research"
    SQL_ANALYTICS = "sql_analytics"
    DATA_PROCESSING = "data_processing"
    REPORT_GENERATION = "report_generation"


class StepActionType(StrEnum):
    """Categories of actions that can be scheduled in a plan step."""

    RETRIEVE_DOCS = "retrieve_docs"
    SEARCH_WEB = "search_web"
    RUN_SQL_READ = "run_sql_read"
    RUN_SQL_WRITE = "run_sql_write"
    EXECUTE_CODE = "execute_code"
    GENERATE_REPORT = "generate_report"
    SEND_WEBHOOK = "send_webhook"
    USER_INTERACTION = "user_interaction"


class PlanStep(BaseModel):
    """Individual atomic unit of work within an execution plan (FR-OR-1, FR-OR-4).

    Steps track prerequisite dependencies, status, execution arguments, and results.
    """

    step_id: str = Field(
        default_factory=lambda: f"step-{uuid4().hex[:8]}",
        description="Unique identifier for this plan step",
    )
    title: str = Field(description="Short human-readable summary of the step")
    description: str = Field(description="Detailed instructions for the assigned agent")
    agent: AgentType = Field(description="Target specialized agent responsible for this step")
    action_type: StepActionType = Field(description="Categorical action type for governance checks")
    action_arguments: dict[str, Any] = Field(
        default_factory=dict,
        description="Arguments passed to the agent or MCP tool",
    )
    dependencies: list[str] = Field(
        default_factory=list,
        description="List of step_ids that must complete before this step can begin",
    )
    status: str = Field(
        default="pending",
        description="Step status: pending, in_progress, awaiting_approval, completed, failed, skipped",
    )
    result: dict[str, Any] | None = Field(
        default=None,
        description="Structured output returned by the executing agent",
    )
    error: str | None = Field(
        default=None,
        description="Error message if this step failed",
    )


class Plan(BaseModel):
    """Ordered multi-step execution plan generated by the Planner (FR-OR-1)."""

    goal: str = Field(description="Original user objective or prompt")
    steps: list[PlanStep] = Field(
        default_factory=list,
        description="Sequential or dependency-linked plan steps",
    )
    current_step_index: int = Field(
        default=0,
        description="Zero-based index of the currently active step",
    )
    is_replan: bool = Field(
        default=False,
        description="True if this plan was revised after a Critic rejection",
    )


class BudgetLimits(BaseModel):
    """Resource constraints enforcing bounded run execution (FR-OR-7).

    Prevents runaway multi-agent loops and unbounded infrastructure costs.
    """

    max_steps: int = Field(default=25, description="Maximum total steps allowed across all agents")
    max_tokens: int = Field(default=50000, description="Cumulative LLM token limit for the run")
    max_cost_usd: float = Field(default=2.00, description="Hard monetary cost ceiling in USD")
    max_wall_clock_seconds: float = Field(
        default=300.0,
        description="Maximum execution duration before timeout",
    )


class BudgetUsage(BaseModel):
    """Real-time resource consumption tracking for an active run (FR-OR-7)."""

    steps_taken: int = Field(default=0, description="Total steps executed so far")
    tokens_used: int = Field(default=0, description="Total LLM prompt + completion tokens used")
    cost_usd: float = Field(default=0.0, description="Estimated monetary spend in USD")
    start_time: datetime = Field(
        default_factory=lambda: datetime.now(UTC),
        description="UTC timestamp when run started",
    )

    def is_exceeded(self, limits: BudgetLimits) -> tuple[bool, str]:
        """Check if any configured budget ceiling has been breached.

        Returns:
            Tuple of (is_breached, reason_string).
        """
        if self.steps_taken >= limits.max_steps:
            return True, f"Exceeded maximum steps ({self.steps_taken} >= {limits.max_steps})"
        if self.tokens_used >= limits.max_tokens:
            return True, f"Exceeded maximum tokens ({self.tokens_used} >= {limits.max_tokens})"
        if self.cost_usd >= limits.max_cost_usd:
            return True, f"Exceeded maximum cost (${self.cost_usd:.2f} >= ${limits.max_cost_usd:.2f})"

        elapsed = (datetime.now(UTC) - self.start_time).total_seconds()
        if elapsed >= limits.max_wall_clock_seconds:
            return (
                True,
                f"Exceeded time limit ({elapsed:.1f}s >= {limits.max_wall_clock_seconds:.1f}s)",
            )

        return False, ""


class ApprovalRequest(BaseModel):
    """Governance pause record when a high-risk action requires human sign-off (FR-OR-6).

    Stored inside the graph state when LangGraph's interrupt() is triggered.
    """

    request_id: str = Field(
        default_factory=lambda: f"appr-{uuid4().hex[:8]}",
        description="Unique approval request ID",
    )
    run_id: str = Field(description="Parent run ID")
    tenant_id: str = Field(description="Tenant scope")
    step_id: str = Field(description="ID of the plan step requesting approval")
    action: str = Field(description="Action name (e.g. 'run_sql_write', 'execute_code')")
    arguments: dict[str, Any] = Field(description="Exact arguments to be approved")
    reason: str = Field(description="Explanation of why approval is required")
    risk_tier: int = Field(default=2, description="Policy risk tier (Tier 2 = High-Risk)")
    created_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
    approved: bool | None = Field(default=None, description="True=approved, False=rejected, None=pending")
    approved_by: str | None = Field(default=None, description="User ID who submitted decision")
    decision_notes: str | None = Field(default=None, description="Optional reviewer feedback")
    approval_token: str | None = Field(
        default=None,
        description="Cryptographically signed HMAC token verifying approval",
    )


class StepEvent(BaseModel):
    """Streaming timeline event emitted during execution (FR-GW-6, FR-OR-9).

    Sent over Server-Sent Events (SSE) to update the frontend timeline in real-time.
    """

    event_id: str = Field(default_factory=lambda: f"evt-{uuid4().hex[:8]}")
    run_id: str = Field(description="Run ID")
    timestamp: datetime = Field(default_factory=lambda: datetime.now(UTC))
    event_type: str = Field(
        description="Event classification: 'plan_created', 'step_start', 'step_complete', 'interrupted', etc."
    )
    agent: str = Field(description="Agent emitting the event")
    payload: dict[str, Any] = Field(default_factory=dict, description="Event data")


# =============================================================================
# State Reducer Functions (FR-OR-2)
# =============================================================================


def append_events(left: list[StepEvent] | None, right: list[StepEvent] | None) -> list[StepEvent]:
    """LangGraph reducer: Appends new timeline events to the historical event log."""
    combined = list(left) if left else []
    if right:
        combined.extend(right)
    return combined


def append_artifacts(
    left: list[dict[str, Any]] | None, right: list[dict[str, Any]] | None
) -> list[dict[str, Any]]:
    """LangGraph reducer: Appends generated artifacts (files, charts, dataframes) to the run."""
    combined = list(left) if left else []
    if right:
        combined.extend(right)
    return combined


def merge_step_results(
    left: dict[str, Any] | None, right: dict[str, Any] | None
) -> dict[str, Any]:
    """LangGraph reducer: Merges newly completed step results into the global step result dictionary."""
    combined = dict(left) if left else {}
    if right:
        combined.update(right)
    return combined


# =============================================================================
# AgentState: TypedDict for LangGraph Graph State (FR-OR-2)
# =============================================================================


class AgentState(TypedDict, total=False):
    """Core state schema flowing through all nodes in the LangGraph supervisor graph.

    Contains the user goal, current execution plan, budget limits and usage,
    accumulated step results, streamable events, and any pending governance interrupt.
    """

    run_id: str
    tenant_id: str
    user_id: str
    goal: str
    status: RunStatus
    plan: Plan | None
    current_step_id: str | None
    step_results: Annotated[dict[str, Any], merge_step_results]
    artifacts: Annotated[list[dict[str, Any]], append_artifacts]
    events: Annotated[list[StepEvent], append_events]
    budget_limits: BudgetLimits
    budget_usage: BudgetUsage
    pending_approval: ApprovalRequest | None
    critic_notes: str | None
    error: str | None
    final_response: str | None
