"""OpenTelemetry distributed tracing setup and correlation ID propagation utilities.

================================================================================
EDUCATIONAL ARCHITECTURE NOTES:
Why Distributed Tracing and W3C Trace Context Propagation?
--------------------------------------------------------------------------------
In a monolithic application, debugging a slow request is simple: you read the call
stack. In a distributed multi-agent platform, a single user query might travel through:
  Client -> API Gateway -> Supervisor Agent -> MCP Tool Server -> Qdrant / Database

If the user waits 4 seconds for an answer, WHERE was the bottleneck? Was it Qdrant?
Was it the LLM generation? Or was it waiting for an AMQP worker?

1. OpenTelemetry Spans & Traces:
   - A "Span" represents a single timed operation (e.g. `vector_search`, `bm25_encode`).
   - A "Trace" is a tree of spans sharing a single unique `trace_id` that tracks the
     entire lifecycle of the request across network boundaries.

2. W3C Trace Context Standard (`traceparent`):
   When crossing network boundaries (such as publishing a message to RabbitMQ or
   calling an MCP server), OpenTelemetry encodes the trace into a standard header:
   `traceparent: 00-4bf92f3577b34da6a3ce929d0e0e4736-00f067aa0ba902b7-01`
   - `4bf92f...` is the 32-character hex Trace ID.
   - `00f067...` is the 16-character hex Parent Span ID.
   The receiver extracts this header using `extract_trace_context()` so its new spans
   become direct children of the caller's span in the trace tree!

3. Correlation ID vs Trace ID:
   - Trace ID is technical, generated by OpenTelemetry for latency waterfalls.
   - Correlation ID (`X-Correlation-ID`) is human-facing and business-scoped, often
     passed by client applications or support teams to locate all logs for an incident.
   `CorrelationIdMiddleware` bridges both: it captures or generates the correlation ID,
   stores it in `contextvars`, and attaches it as an attribute to the active OTel span.
================================================================================
"""

import uuid
from collections.abc import Awaitable, Callable
from typing import Any

from opentelemetry import trace
from opentelemetry.exporter.otlp.proto.grpc.trace_exporter import OTLPSpanExporter
from opentelemetry.sdk.resources import SERVICE_NAME, Resource
from opentelemetry.sdk.trace import TracerProvider
from opentelemetry.sdk.trace.export import BatchSpanProcessor, SimpleSpanProcessor
from opentelemetry.trace.propagation.tracecontext import TraceContextTextMapPropagator
from starlette.middleware.base import BaseHTTPMiddleware
from starlette.requests import Request
from starlette.responses import Response

from libs.common.logging import correlation_id_ctx, get_logger

logger = get_logger(__name__)

# Standard HTTP correlation header names
CORRELATION_ID_HEADER = "X-Correlation-ID"
REQUEST_ID_HEADER = "X-Request-ID"


def setup_telemetry(
    service_name: str,
    otlp_endpoint: str | None = None,
    insecure: bool = True,
    use_batch_exporter: bool = True,
) -> TracerProvider:
    """Initialize OpenTelemetry tracer provider with OTLP gRPC exporter.

    Args:
        service_name: Name of the microservice (e.g. 'gateway', 'mcp-sql').
        otlp_endpoint: OTLP collector gRPC endpoint (e.g. 'localhost:4317').
                       If None, spans are tracked in memory without remote export.
        insecure: If True, uses unencrypted gRPC (standard for internal k8s clusters).
        use_batch_exporter: True for production batching (flushes asynchronously in background);
                            False for immediate simple export (useful during tests).

    Returns:
        Configured TracerProvider instance.
    """
    resource = Resource.create({SERVICE_NAME: service_name})
    provider = TracerProvider(resource=resource)

    if (
        otlp_endpoint
        and otlp_endpoint.strip()
        and otlp_endpoint.lower() not in ("none", "false", "0")
    ):
        try:
            exporter = OTLPSpanExporter(
                endpoint=otlp_endpoint,
                insecure=insecure,
            )
            processor = (
                BatchSpanProcessor(exporter)
                if use_batch_exporter
                else SimpleSpanProcessor(exporter)
            )
            provider.add_span_processor(processor)
            logger.info("OTel exporter configured", endpoint=otlp_endpoint, service=service_name)
        except Exception as exc:
            logger.warning(
                "Failed to configure OTLP exporter, running without remote export", error=str(exc)
            )

    trace.set_tracer_provider(provider)
    return provider


def inject_trace_context(carrier: dict[str, Any] | None = None) -> dict[str, Any]:
    """Inject W3C trace context (traceparent) into a carrier dict.

    Use this before publishing a message to RabbitMQ headers or making an MCP request:
        headers = inject_trace_context({})
        rabbitmq_channel.basic_publish(..., headers=headers)
    """
    if carrier is None:
        carrier = {}
    TraceContextTextMapPropagator().inject(carrier)
    return carrier


def extract_trace_context(carrier: dict[str, Any]) -> Any:
    """Extract W3C trace context from incoming carrier dict (HTTP/RabbitMQ/MCP).

    Use this when consuming a message from a background queue:
        context = extract_trace_context(message.headers)
        with tracer.start_as_current_span("process_task", context=context):
            ...
    """
    return TraceContextTextMapPropagator().extract(carrier)


class CorrelationIdMiddleware(BaseHTTPMiddleware):
    """FastAPI/Starlette middleware ensuring every request has a correlation ID.

    Behavior:
    1. Inspects incoming headers for `X-Correlation-ID` or `X-Request-ID`.
    2. If missing, generates a new UUID4 correlation ID.
    3. Sets the correlation ID in Python's task-local `correlation_id_ctx`.
    4. Attaches `app.correlation_id` attribute to the active OpenTelemetry span.
    5. Injects `X-Correlation-ID` header into the outgoing HTTP response.
    """

    async def dispatch(
        self, request: Request, call_next: Callable[[Request], Awaitable[Response]]
    ) -> Response:
        # Check incoming headers for existing correlation ID from client
        incoming_id = request.headers.get(CORRELATION_ID_HEADER) or request.headers.get(
            REQUEST_ID_HEADER
        )
        corr_id = incoming_id.strip() if incoming_id else str(uuid.uuid4())

        # Set in contextvar for automatic structlog enrichment
        token = correlation_id_ctx.set(corr_id)

        # Set correlation ID attribute on active span if present
        current_span = trace.get_current_span()
        if current_span and current_span.is_recording():
            current_span.set_attribute("app.correlation_id", corr_id)

        try:
            response = await call_next(request)
            response.headers[CORRELATION_ID_HEADER] = corr_id
            return response
        finally:
            correlation_id_ctx.reset(token)
